import { BookRecord, BookStoreData, BookStoreSettings } from "@/types/books";

const now = new Date().toISOString();

export const defaultBookStoreSettings: BookStoreSettings = {
  currency: "PHP",
  storeName: "Church Planting Movement Books",
  storefrontHeadline: "Books for discipleship, leadership, and ministry growth.",
  supportEmail: "books@churchplantingmovement.local",
  returnPolicy: "Digital book purchases are final unless a file is defective or inaccessible.",
  shippingMessage: "Digital delivery is instant after checkout. Physical shipping can be configured later.",
  featuredCollectionTitle: "Books Handpicked for Leaders",
  lowStockThreshold: 20,
  showAuthorsOnCards: true,
  showBookFormats: true,
  enableRecommendations: true,
  enableBestsellersStrip: true,
  allowPreorders: false,
  inventoryTrackingEnabled: true,
};

export const defaultBooks: BookRecord[] = [
  {
    id: "kingdom-foundations",
    title: "Kingdom Foundations",
    author: "Pastor Elias Monte",
    category: "Discipleship",
    price: 490,
    pages: 184,
    accentFrom: "from-sky-500",
    accentTo: "to-cyan-400",
    summary: "A guided starter for believers building Scripture, prayer, and service rhythms.",
    description: "A clear starting point for new believers building daily rhythms of prayer, Scripture, and service. Includes chapter reflection prompts, discussion questions, and action guides for small groups.",
    tagline: "Start strong with biblical habits.",
    sku: "BK-KF-001",
    isbn: "978-621-000-1001",
    language: "English",
    format: "EBOOK",
    inventory: 999,
    featured: true,
    allowDiscounts: true,
    status: "PUBLISHED",
    publishedAt: now,
    releaseDate: now,
    monthlySales: 42,
    yearlySales: 356,
    monthlyRevenue: 20580,
    yearlyRevenue: 174440,
    totalSales: 640,
    totalRevenue: 313600,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "shepherding-teams",
    title: "Shepherding Teams",
    author: "Naomi Villanueva",
    category: "Leadership",
    price: 650,
    pages: 212,
    accentFrom: "from-emerald-500",
    accentTo: "to-teal-400",
    summary: "A ministry leadership playbook for building healthy, scalable volunteer teams.",
    description: "Practical team-building guidance for ministry leaders scaling volunteers without losing care. Covers recruiting, onboarding, conflict management, and sustainable rhythms.",
    tagline: "Lead volunteers with clarity.",
    sku: "BK-ST-002",
    isbn: "978-621-000-1002",
    language: "English",
    format: "EBOOK",
    inventory: 999,
    featured: true,
    allowDiscounts: true,
    status: "PUBLISHED",
    publishedAt: now,
    releaseDate: now,
    monthlySales: 38,
    yearlySales: 288,
    monthlyRevenue: 24700,
    yearlyRevenue: 187200,
    totalSales: 512,
    totalRevenue: 332800,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "disciple-maker-playbook",
    title: "Disciple-Maker Playbook",
    author: "Joel Ramirez",
    category: "Ministry",
    price: 720,
    pages: 236,
    accentFrom: "from-indigo-500",
    accentTo: "to-blue-400",
    summary: "Frameworks and worksheets for multiplying disciple-making communities.",
    description: "Frameworks, worksheets, and conversation prompts for multiplying discipleship groups. Ideal for leaders who want a practical, reproducible process.",
    tagline: "Build a repeatable disciple-making process.",
    sku: "BK-DMP-003",
    isbn: "978-621-000-1003",
    language: "English",
    format: "EBOOK",
    inventory: 999,
    featured: true,
    allowDiscounts: true,
    status: "PUBLISHED",
    publishedAt: now,
    releaseDate: now,
    monthlySales: 51,
    yearlySales: 401,
    monthlyRevenue: 36720,
    yearlyRevenue: 288720,
    totalSales: 710,
    totalRevenue: 511200,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "gospel-conversations",
    title: "Gospel Conversations",
    author: "Marielle Cruz",
    category: "Evangelism",
    price: 540,
    pages: 168,
    accentFrom: "from-amber-500",
    accentTo: "to-orange-400",
    summary: "A practical guide to natural, honest gospel conversations in daily life.",
    description: "Simple ways to speak about Jesus with confidence in everyday relationships and real situations. Includes dialogue examples and follow-up strategies.",
    tagline: "Turn everyday talk into meaningful witness.",
    sku: "BK-GC-004",
    isbn: "978-621-000-1004",
    language: "English",
    format: "EBOOK",
    inventory: 999,
    featured: false,
    allowDiscounts: true,
    status: "PUBLISHED",
    publishedAt: now,
    releaseDate: now,
    monthlySales: 24,
    yearlySales: 190,
    monthlyRevenue: 12960,
    yearlyRevenue: 102600,
    totalSales: 330,
    totalRevenue: 178200,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "family-altar-guide",
    title: "Family Altar Guide",
    author: "Grace Dela Torre",
    category: "Family",
    price: 580,
    pages: 190,
    accentFrom: "from-rose-500",
    accentTo: "to-pink-400",
    summary: "Weekly devotion plans for shaping discipleship culture at home.",
    description: "Weekly devotion plans and family discipleship practices for homes of every season. Designed for parents, mentors, and household leaders.",
    tagline: "Shape the spiritual culture at home.",
    sku: "BK-FAG-005",
    isbn: "978-621-000-1005",
    language: "English",
    format: "EBOOK",
    inventory: 999,
    featured: false,
    allowDiscounts: true,
    status: "PUBLISHED",
    publishedAt: now,
    releaseDate: now,
    monthlySales: 18,
    yearlySales: 144,
    monthlyRevenue: 10440,
    yearlyRevenue: 83520,
    totalSales: 278,
    totalRevenue: 161240,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prayer-rhythm-journal",
    title: "Prayer Rhythm Journal",
    author: "Daniel Flores",
    category: "Prayer",
    price: 430,
    pages: 144,
    accentFrom: "from-violet-500",
    accentTo: "to-fuchsia-400",
    summary: "Guided prompts for building a steady, reflective prayer life.",
    description: "Guided reflections and structured prompts to deepen consistency in prayer and listening. Includes journaling exercises and prayer trackers.",
    tagline: "Move from rushed prayers to rooted communion.",
    sku: "BK-PRJ-006",
    isbn: "978-621-000-1006",
    language: "English",
    format: "EBOOK",
    inventory: 999,
    featured: false,
    allowDiscounts: true,
    status: "PUBLISHED",
    publishedAt: now,
    releaseDate: now,
    monthlySales: 12,
    yearlySales: 98,
    monthlyRevenue: 5160,
    yearlyRevenue: 42140,
    totalSales: 186,
    totalRevenue: 79980,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "servant-leader-handbook",
    title: "Servant Leader Handbook",
    author: "Micah Santos",
    category: "Leadership",
    price: 695,
    pages: 224,
    accentFrom: "from-slate-700",
    accentTo: "to-slate-500",
    summary: "Leadership wisdom shaped by humility, conviction, and mission.",
    description: "Field-tested guidance for leaders who want authority shaped by humility and mission. Useful for team leaders, ministry heads, and executive pastors.",
    tagline: "Lead with conviction and service.",
    sku: "BK-SLH-007",
    isbn: "978-621-000-1007",
    language: "English",
    format: "EBOOK",
    inventory: 999,
    featured: true,
    allowDiscounts: true,
    status: "PUBLISHED",
    publishedAt: now,
    releaseDate: now,
    monthlySales: 33,
    yearlySales: 260,
    monthlyRevenue: 22935,
    yearlyRevenue: 180700,
    totalSales: 468,
    totalRevenue: 325260,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "youth-fire-starter",
    title: "Youth Fire Starter",
    author: "Abigail Reyes",
    category: "Youth Ministry",
    price: 610,
    pages: 176,
    accentFrom: "from-red-500",
    accentTo: "to-orange-500",
    summary: "Youth ministry sessions and mentoring ideas that drive engagement.",
    description: "Session outlines and mentoring ideas for youth leaders building engaged small groups. Designed for practical weekly use.",
    tagline: "Equip students to own their faith.",
    sku: "BK-YFS-008",
    isbn: "978-621-000-1008",
    language: "English",
    format: "EBOOK",
    inventory: 999,
    featured: false,
    allowDiscounts: true,
    status: "PUBLISHED",
    publishedAt: now,
    releaseDate: now,
    monthlySales: 27,
    yearlySales: 212,
    monthlyRevenue: 16470,
    yearlyRevenue: 129320,
    totalSales: 389,
    totalRevenue: 237290,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "mission-house-blueprint",
    title: "Mission House Blueprint",
    author: "Samuel Ortega",
    category: "Church Growth",
    price: 760,
    pages: 248,
    accentFrom: "from-lime-500",
    accentTo: "to-emerald-400",
    summary: "A strategic handbook for building healthy sending systems in the local church.",
    description: "A strategic handbook for planting healthy teams, systems, and sending culture. Ideal for churches building ministry infrastructure.",
    tagline: "Design a church that sends people well.",
    sku: "BK-MHB-009",
    isbn: "978-621-000-1009",
    language: "English",
    format: "EBOOK",
    inventory: 999,
    featured: true,
    allowDiscounts: true,
    status: "PUBLISHED",
    publishedAt: now,
    releaseDate: now,
    monthlySales: 16,
    yearlySales: 121,
    monthlyRevenue: 12160,
    yearlyRevenue: 91960,
    totalSales: 240,
    totalRevenue: 182400,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "faithful-finish",
    title: "Faithful Finish",
    author: "Ruth Mendoza",
    category: "Spiritual Growth",
    price: 520,
    pages: 160,
    accentFrom: "from-cyan-500",
    accentTo: "to-blue-500",
    summary: "Encouragement for believers pursuing endurance and mature faith.",
    description: "Encouragement and reflection for believers who want endurance, maturity, and long obedience. Best for personal reading and discipleship cohorts.",
    tagline: "Stay steady for the long journey.",
    sku: "BK-FF-010",
    isbn: "978-621-000-1010",
    language: "English",
    format: "EBOOK",
    inventory: 999,
    featured: false,
    allowDiscounts: true,
    status: "PUBLISHED",
    publishedAt: now,
    releaseDate: now,
    monthlySales: 9,
    yearlySales: 80,
    monthlyRevenue: 4680,
    yearlyRevenue: 41600,
    totalSales: 152,
    totalRevenue: 79040,
    createdAt: now,
    updatedAt: now,
  },
];

export const defaultBookStoreData: BookStoreData = {
  books: defaultBooks,
  settings: defaultBookStoreSettings,
  updatedAt: now,
};export type SampleBook = {
  id: string;
  title: string;
  author: string;
  category: string;
  price: number;
  pages: number;
  accentFrom: string;
  accentTo: string;
  description: string;
  tagline: string;
};

export const sampleBooks: SampleBook[] = [
  {
    id: "kingdom-foundations",
    title: "Kingdom Foundations",
    author: "Pastor Elias Monte",
    category: "Discipleship",
    price: 490,
    pages: 184,
    accentFrom: "from-sky-500",
    accentTo: "to-cyan-400",
    description: "A clear starting point for new believers building daily rhythms of prayer, Scripture, and service.",
    tagline: "Start strong with biblical habits.",
  },
  {
    id: "shepherding-teams",
    title: "Shepherding Teams",
    author: "Naomi Villanueva",
    category: "Leadership",
    price: 650,
    pages: 212,
    accentFrom: "from-emerald-500",
    accentTo: "to-teal-400",
    description: "Practical team-building guidance for ministry leaders scaling volunteers without losing care.",
    tagline: "Lead volunteers with clarity.",
  },
  {
    id: "disciple-maker-playbook",
    title: "Disciple-Maker Playbook",
    author: "Joel Ramirez",
    category: "Ministry",
    price: 720,
    pages: 236,
    accentFrom: "from-indigo-500",
    accentTo: "to-blue-400",
    description: "Frameworks, worksheets, and conversation prompts for multiplying discipleship groups.",
    tagline: "Build a repeatable disciple-making process.",
  },
  {
    id: "gospel-conversations",
    title: "Gospel Conversations",
    author: "Marielle Cruz",
    category: "Evangelism",
    price: 540,
    pages: 168,
    accentFrom: "from-amber-500",
    accentTo: "to-orange-400",
    description: "Simple ways to speak about Jesus with confidence in everyday relationships and real situations.",
    tagline: "Turn everyday talk into meaningful witness.",
  },
  {
    id: "family-altar-guide",
    title: "Family Altar Guide",
    author: "Grace Dela Torre",
    category: "Family",
    price: 580,
    pages: 190,
    accentFrom: "from-rose-500",
    accentTo: "to-pink-400",
    description: "Weekly devotion plans and family discipleship practices for homes of every season.",
    tagline: "Shape the spiritual culture at home.",
  },
  {
    id: "prayer-rhythm-journal",
    title: "Prayer Rhythm Journal",
    author: "Daniel Flores",
    category: "Prayer",
    price: 430,
    pages: 144,
    accentFrom: "from-violet-500",
    accentTo: "to-fuchsia-400",
    description: "Guided reflections and structured prompts to deepen consistency in prayer and listening.",
    tagline: "Move from rushed prayers to rooted communion.",
  },
  {
    id: "servant-leader-handbook",
    title: "Servant Leader Handbook",
    author: "Micah Santos",
    category: "Leadership",
    price: 695,
    pages: 224,
    accentFrom: "from-slate-700",
    accentTo: "to-slate-500",
    description: "Field-tested guidance for leaders who want authority shaped by humility and mission.",
    tagline: "Lead with conviction and service.",
  },
  {
    id: "youth-fire-starter",
    title: "Youth Fire Starter",
    author: "Abigail Reyes",
    category: "Youth Ministry",
    price: 610,
    pages: 176,
    accentFrom: "from-red-500",
    accentTo: "to-orange-500",
    description: "Session outlines and mentoring ideas for youth leaders building engaged small groups.",
    tagline: "Equip students to own their faith.",
  },
  {
    id: "mission-house-blueprint",
    title: "Mission House Blueprint",
    author: "Samuel Ortega",
    category: "Church Growth",
    price: 760,
    pages: 248,
    accentFrom: "from-lime-500",
    accentTo: "to-emerald-400",
    description: "A strategic handbook for planting healthy teams, systems, and sending culture.",
    tagline: "Design a church that sends people well.",
  },
  {
    id: "faithful-finish",
    title: "Faithful Finish",
    author: "Ruth Mendoza",
    category: "Spiritual Growth",
    price: 520,
    pages: 160,
    accentFrom: "from-cyan-500",
    accentTo: "to-blue-500",
    description: "Encouragement and reflection for believers who want endurance, maturity, and long obedience.",
    tagline: "Stay steady for the long journey.",
  },
];

export function getSampleBookById(bookId: string) {
  return sampleBooks.find((book) => book.id === bookId);
}